name: BuildDeployTestApp

on:
  push:
    branches: [master]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest
    steps:
     - uses : actions/checkout@v4

     - name: SetupNodeJS
       uses: actions/setup-node@v4
       with:
         node-version: 18.x
     - name: Install dependencies
       run: npm install 

     - name: BuildApp
       run: npm run build 
       
  deploy-angular-app:
       runs-on : ubuntu-latest
       needs: build-angular-app
      steps: 
        name: Test
        run : echo "tests running"     
  
