name: EnvVar Programmatic
on:
  push:
    branches:
      - master
env:
  CHANNEL_NAME: CodeGeeks

jobs:
  envdemo:
    runs-on: ubuntu-latest
    steps:
      - name: EnvDemo
        run: echo "Hello, $CHANNEL_NAME !"

      - name: Set Envariables programatically  
        run: echo "COUNT=100000" >> $GITHUB_ENV
        
      - name: Access env variable
        run: echo ${{env.COUNT}}        
  
