name: Mannual Worlkflow

on:
  workflow_dispatch:
    inputs:
      name:
       description: 'Name'
       type: string
       default: 'Anil'
      age:
       description: 'Age'
       type: number
       required: true
         
jobs:
  manual:
   runs-on: ubuntu-latest
   
   steps:
     - name: MyName
       run: echo "${{inputs.name}}"
  
     - name: MyAge
       run: echo "${{inputs.age}}"
 
